import Head from "next/head"
import styles from "../styles/Home.module.css"
import Image from "next/image"
import jamstack from "../assets/JAMstack.png"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jamstack site</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className={styles.main}>
        <Image
          alt="jamstack"
          src={jamstack}
          layout="fill"
          objectFit="scale-down"
          quality={100}
          className={styles.bgImage}
        />
      </main>
    </div>
  )
}

