import Head from "next/head"
import styles from "../styles/Home.module.css"
import NavBar from "../components/navbar"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Agence Pickbeam Developpement web à Toulouse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to PickBeam !</h1>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/sbrcode/jam-beam-site"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <span className={styles.logo}>Sylvain</span>
        </a>
      </footer>
    </div>
  )
}

